//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BionicFinalProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BionicFinalProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Против компьютера.
        /// </summary>
        public static string AIGame {
            get {
                return ResourceManager.GetString("AIGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ход черных - .
        /// </summary>
        public static string BlackTurn {
            get {
                return ResourceManager.GetString("BlackTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выиграли черные.
        /// </summary>
        public static string BlackWon {
            get {
                return ResourceManager.GetString("BlackWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя отменить ход.
        /// </summary>
        public static string CanNotReturnStep {
            get {
                return ResourceManager.GetString("CanNotReturnStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черные.
        /// </summary>
        public static string CheckBlack {
            get {
                return ResourceManager.GetString("CheckBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP противника.
        /// </summary>
        public static string CheckIP {
            get {
                return ResourceManager.GetString("CheckIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string CheckLogOut {
            get {
                return ResourceManager.GetString("CheckLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите режим игры.
        /// </summary>
        public static string CheckMode {
            get {
                return ResourceManager.GetString("CheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать игру.
        /// </summary>
        public static string CheckStartGame {
            get {
                return ResourceManager.GetString("CheckStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Белые.
        /// </summary>
        public static string CheckWhite {
            get {
                return ResourceManager.GetString("CheckWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши шашки:.
        /// </summary>
        public static string CheckYourCheckers {
            get {
                return ResourceManager.GetString("CheckYourCheckers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка соединения.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сюда ходить нельзя!.
        /// </summary>
        public static string ErrorCanNotMove {
            get {
                return ResourceManager.GetString("ErrorCanNotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У этой шашки нет ходов.
        /// </summary>
        public static string ErrorHasNoMoves {
            get {
                return ResourceManager.GetString("ErrorHasNoMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ходите только своими шашками!.
        /// </summary>
        public static string ErrorNotYourCheckers {
            get {
                return ResourceManager.GetString("ErrorNotYourCheckers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти в главное меню.
        /// </summary>
        public static string ExitToMainMenu {
            get {
                return ResourceManager.GetString("ExitToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра.
        /// </summary>
        public static string GameMenu {
            get {
                return ResourceManager.GetString("GameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игр сыграно: .
        /// </summary>
        public static string GamePlayed {
            get {
                return ResourceManager.GetString("GamePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игр выиграно: .
        /// </summary>
        public static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мне некуда ходить! Сдаюсь!.
        /// </summary>
        public static string ICanNotMove {
            get {
                return ResourceManager.GetString("ICanNotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальная игра.
        /// </summary>
        public static string LocalGame {
            get {
                return ResourceManager.GetString("LocalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное имя или пароль.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок.
        /// </summary>
        public static string MenuPlayer {
            get {
                return ResourceManager.GetString("MenuPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string MenuStatistics {
            get {
                return ResourceManager.GetString("MenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно бить!.
        /// </summary>
        public static string MustAttack {
            get {
                return ResourceManager.GetString("MustAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать новую игру.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сетевая игра (введите IP).
        /// </summary>
        public static string OnlineGame {
            get {
                return ResourceManager.GetString("OnlineGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гость.
        /// </summary>
        public static string Player1Guest {
            get {
                return ResourceManager.GetString("Player1Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок 2.
        /// </summary>
        public static string Player2 {
            get {
                return ResourceManager.GetString("Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Ход игры.
        /// </summary>
        public static string ProgressList {
            get {
                return ResourceManager.GetString("ProgressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональный вход позволит выводить ваше имя в игре, а также сохранять статистику.
        /// </summary>
        public static string RegisterBetter {
            get {
                return ResourceManager.GetString("RegisterBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить ход.
        /// </summary>
        public static string ReturnStep {
            get {
                return ResourceManager.GetString("ReturnStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраненная игра - сетевая. Продолжить можно только локально!.
        /// </summary>
        public static string SavedGameIsOnline {
            get {
                return ResourceManager.GetString("SavedGameIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveGame {
            get {
                return ResourceManager.GetString("SaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подождите своего хода.
        /// </summary>
        public static string WaitYourTurn {
            get {
                return ResourceManager.GetString("WaitYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать, .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ход белых  - .
        /// </summary>
        public static string WhiteTurn {
            get {
                return ResourceManager.GetString("WhiteTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выиграли белые.
        /// </summary>
        public static string WhiteWon {
            get {
                return ResourceManager.GetString("WhiteWon", resourceCulture);
            }
        }
    }
}
