//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BionicFinalProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ua {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ua() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BionicFinalProject.Properties.Resources.ua", typeof(Resources_ua).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проти комп&apos;ютера.
        /// </summary>
        public static string AIGame {
            get {
                return ResourceManager.GetString("AIGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хід чорних - .
        /// </summary>
        public static string BlackTurn {
            get {
                return ResourceManager.GetString("BlackTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виграли чорні.
        /// </summary>
        public static string BlackWon {
            get {
                return ResourceManager.GetString("BlackWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можна відмінити хід.
        /// </summary>
        public static string CanNotReturnStep {
            get {
                return ResourceManager.GetString("CanNotReturnStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чорні.
        /// </summary>
        public static string CheckBlack {
            get {
                return ResourceManager.GetString("CheckBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP противника.
        /// </summary>
        public static string CheckIP {
            get {
                return ResourceManager.GetString("CheckIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string CheckLogOut {
            get {
                return ResourceManager.GetString("CheckLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть режим гри.
        /// </summary>
        public static string CheckMode {
            get {
                return ResourceManager.GetString("CheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почати гру.
        /// </summary>
        public static string CheckStartGame {
            get {
                return ResourceManager.GetString("CheckStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Білі.
        /// </summary>
        public static string CheckWhite {
            get {
                return ResourceManager.GetString("CheckWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваші шашки:.
        /// </summary>
        public static string CheckYourCheckers {
            get {
                return ResourceManager.GetString("CheckYourCheckers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка з&apos;єднання.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сюди ходити не можна!.
        /// </summary>
        public static string ErrorCanNotMove {
            get {
                return ResourceManager.GetString("ErrorCanNotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця шашка не має ходів.
        /// </summary>
        public static string ErrorHasNoMoves {
            get {
                return ResourceManager.GetString("ErrorHasNoMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це не ваша шашка!.
        /// </summary>
        public static string ErrorNotYourCheckers {
            get {
                return ResourceManager.GetString("ErrorNotYourCheckers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти до головного меню.
        /// </summary>
        public static string ExitToMainMenu {
            get {
                return ResourceManager.GetString("ExitToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гра.
        /// </summary>
        public static string GameMenu {
            get {
                return ResourceManager.GetString("GameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зіграно ігор: .
        /// </summary>
        public static string GamePlayed {
            get {
                return ResourceManager.GetString("GamePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виграно ігор: .
        /// </summary>
        public static string GameWon {
            get {
                return ResourceManager.GetString("GameWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меня немає куди ходити!.
        /// </summary>
        public static string ICanNotMove {
            get {
                return ResourceManager.GetString("ICanNotMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити.
        /// </summary>
        public static string LoadGame {
            get {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальна гра.
        /// </summary>
        public static string LocalGame {
            get {
                return ResourceManager.GetString("LocalGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірна пара ім&apos;я/пароль.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гравець.
        /// </summary>
        public static string MenuPlayer {
            get {
                return ResourceManager.GetString("MenuPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string MenuStatistics {
            get {
                return ResourceManager.GetString("MenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треба бити!.
        /// </summary>
        public static string MustAttack {
            get {
                return ResourceManager.GetString("MustAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпочати нову гру.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мережева гра (введіть IP).
        /// </summary>
        public static string OnlineGame {
            get {
                return ResourceManager.GetString("OnlineGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гість.
        /// </summary>
        public static string Player1Guest {
            get {
                return ResourceManager.GetString("Player1Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гравець 2.
        /// </summary>
        public static string Player2 {
            get {
                return ResourceManager.GetString("Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Хід гри.
        /// </summary>
        public static string ProgressList {
            get {
                return ResourceManager.GetString("ProgressList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персональний вхід дозволить виводити ім&apos;я у грі та зберігати статистику.
        /// </summary>
        public static string RegisterBetter {
            get {
                return ResourceManager.GetString("RegisterBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватися.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити хід.
        /// </summary>
        public static string ReturnStep {
            get {
                return ResourceManager.GetString("ReturnStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цю мережеву гру можна продовжити тільки локально!.
        /// </summary>
        public static string SavedGameIsOnline {
            get {
                return ResourceManager.GetString("SavedGameIsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string SaveGame {
            get {
                return ResourceManager.GetString("SaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чекайте, зараз не ваш хід.
        /// </summary>
        public static string WaitYourTurn {
            get {
                return ResourceManager.GetString("WaitYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо, .
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хід білих  - .
        /// </summary>
        public static string WhiteTurn {
            get {
                return ResourceManager.GetString("WhiteTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Білі виграли.
        /// </summary>
        public static string WhiteWon {
            get {
                return ResourceManager.GetString("WhiteWon", resourceCulture);
            }
        }
    }
}
